### PR TITLE
Binary-messaging

### LINKED ISSUE #9: Add list of binary buffers in xmessage
Currently, the ``buffers`` member is missing in ``xmessage``. It is a requirement for the implementation of the COMM protocol.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #9.

### CODE REVIEW

**Comment by JohanMabille** [comment]
- `std::list` => `std::vector`
- Add a default value for the buffer argument in the publisher, so you don't have to instantiate it when you don't need it.

**Comment by SylvainCorlay** [comment]
Rebased, and now with a `using buffer_sequence = std::vector<zmq::message_t>`.

**Comment by SylvainCorlay** [comment]
Do we want to have a static const empty buffer sequence as a default argument where it makes sense?

**Comment by SylvainCorlay** [comment]
@JohanMabille this is ready to go!

**Pull request merged**
