### PR TITLE
Fix build error and improve buildsystem

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Hey @jcfr thanks for contributing.

Concerning the move of the headers that were in `src`, their location was intentional. Only the headers meant to be used as part of the API are public and placed in `include/xeus`. The ones in `src` are only used internally in xeus. If you are building a kernel with `xeus`, and you feel that you need something from these headers, let us know and we can help.

**Comment by SylvainCorlay** [comment]
Reading up you PR, there seems to be multiple items, one being to update to a more recent version of `cryptopp`. We have been pinning this dependency at `5.6.5` for a long time, and indeed, it would make sense to support more recent version. I think that this item deserves a PR by itself.

I am not quite sure about the issue that you have with uuid.

Btw, feel free to hop on the developer chat room https://gitter.im/QuantStack/Lobby.

**Comment by jcfr** [comment]
Thanks for the review :+1: , I will  submit multiple PR.

>  you feel that you need something

The goal is to integrate xeus with the Qt event loop of an application that embed python.

I will follow up with a more reasonable proposal.

**Comment by jcfr** [comment]
> We have been pinning this dependency at 5.6.5 for a long time, and indeed,

I also have few change improving [CryptoPP-cmake](https://github.com/noloader/cryptopp-cmake/compare/master...jcfr:miscellaneous-tweaks)

**Comment by SylvainCorlay** [comment]
> > you feel that you need something
>
> I will follow up with a more reasonable proposal.
>

Thanks! Looking forward to help. (I did not mean to be dry in this review). Don't hesitate to hop on the chat.

> > We have been pinning this dependency at 5.6.5 for a long time, and indeed,
> 
> I also have few change improving CryptoPP-cmake

👍 

> The goal is to integrate xeus with the Qt event loop of an application that embed python

Now we are talking! We also intend on making a python kernel with xeus, but have not gotten around to start it.

**Comment by jcfr** [comment]
> Thanks! Looking forward to help. (I did not mean to be dry in this review).

No problem :smile: 

>  Don't hesitate to hop on the chat.

Will do when I have more material to start discussion

**Pull request closed without merging**
