### PR TITLE
Use shared library for cryptopp

### LINKED ISSUE #113: Please consider using pkg-config for cryptopp
https://github.com/QuantStack/xeus/blob/master/CMakeLists.txt#L58

```cppcrypto``` dropped ```cmake``` support. There is ```crypto-cmake``` project that breaks: https://github.com/noloader/cryptopp-cmake/issues/45

If the project doesn't officially support ```cmake```, you probably shouldn't insist on expecting it.

In the FreeBSD port, I have this patch:
```
+FIND_PACKAGE(PkgConfig)
 find_package(nlohmann_json 3.2.0 REQUIRED)
 find_package(xtl 0.5 REQUIRED)
 find_package(cppzmq 4.3.0 REQUIRED)
-find_package(cryptopp REQUIRED)
+pkg_check_modules(cryptopp libcryptopp REQUIRED)
```
that works fine with ```cryptocpp``` project as it is distributed.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #113 
cc @yurivict

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Now the shared library is both build on conda-forge and quantforge.

**Comment by SylvainCorlay** [comment]
@yurivict if you can confirm this works for you, that would be great.

**Comment by yurivict** [comment]
Link fails:
```
FAILED: libxeus.so.1.0.1 
: && /usr/bin/c++ -fPIC -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -fstack-protector -L/usr/local/lib -shared -Wl,-soname,libxeus.so.1 -o libxeus.so.1.0.1 CMakeFiles/xeus.dir/src/xauthentication.cpp.o CMakeFiles/xeus.dir/src/xcomm.cpp.o CMakeFiles/xeus.dir/src/xguid.cpp.o CMakeFiles/xeus.dir/src/xheartbeat.cpp.o CMakeFiles/xeus.dir/src/xhistory_manager.cpp.o CMakeFiles/xeus.dir/src/xinput.cpp.o CMakeFiles/xeus.dir/src/xin_memory_history_manager.cpp.o CMakeFiles/xeus.dir/src/xinterpreter.cpp.o CMakeFiles/xeus.dir/src/xkernel.cpp.o CMakeFiles/xeus.dir/src/xkernel_configuration.cpp.o CMakeFiles/xeus.dir/src/xkernel_core.cpp.o CMakeFiles/xeus.dir/src/xmessage.cpp.o CMakeFiles/xeus.dir/src/xmock_interpreter.cpp.o CMakeFiles/xeus.dir/src/xmiddleware.cpp.o CMakeFiles/xeus.dir/src/xpublisher.cpp.o CMakeFiles/xeus.dir/src/xserver.cpp.o CMakeFiles/xeus.dir/src/xserver_zmq.cpp.o  -lcryptopp-shared /usr/local/lib/libuuid.so /usr/local/lib/libzmq.so && :
/usr/bin/ld: cannot find -lcryptopp-shared
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SylvainCorlay** [comment]
Added an alias for cryptopp-shared in the case of cryptopp-config. Hopefully this will work now.

**Comment by yurivict** [comment]
rev.51f37cb now fails in configure:
```
--   Found libcryptopp, version 7.0
CMake Error at CMakeLists.txt:86 (add_library):
  add_library cannot create ALIAS target "cryptopp-shared" because target
  "/usr/local/lib/libcryptopp.so" does not already exist.


CMake Error at CMakeLists.txt:88 (add_library):
  add_library cannot create ALIAS target "cryptopp-static" because target
  "/usr/local/lib/libcryptopp.a" does not already exist.
```

**Comment by SylvainCorlay** [comment]
Hey @yurivict I have improved the CMake to support both pkg-config and cmake builds of cryptopp.

The use of the shared object for cryptopp is enabled by the `XEUS_USE_SHARED_CRYPTOPP` cmake option which is set to false by default.

**Comment by yurivict** [comment]
rev. 350028b works fine, thank you.

**Pull request merged**
