### PR TITLE
update json.hpp to latest

### PR DESCRIPTION
**Pull request by spennihana**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks! Did you pick it from the last tagged release?

**Comment by SylvainCorlay** [comment]
Note for self: this will require us to remove the hack for `std::pair` in https://github.com/QuantStack/xwidgets/blob/master/include/xwidgets/xlink.hpp

**Comment by spennihana** [comment]
Yes this comes from the 3.0.1 tagged release.

**Comment by SylvainCorlay** [comment]
Thanks, sorry for taking so much time. I had to test that it works with the downstream projects.

**Pull request merged**
