### PR TITLE
Fall back to pkg-config for cryptopp

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Cc @yurivict. Let me know if you find the time to try this out! Hopefully this will solve for your issue.

**Comment by yurivict** [comment]
1b0b97b works now.

One problem though: it should be ```PRIVATE cryptopp```, not ```PRIVATE cryptopp-static```. Not sure why static lib isn't found, but you should only use shared libs. Static libs can be deleted, the default should be shared libs for all libraries.

**Comment by SylvainCorlay** [comment]
> 1b0b97b works now.

Great!

> One problem though: it should be ```PRIVATE cryptopp```, not ```PRIVATE cryptopp-static```. Not sure why static lib isn't found, but you should only use shared libs. Static libs can be deleted, the default should be shared libs for all libraries.

At the moment, we only building the static library in the conda package. cryptopp 8.0 is out, so I will use this occasion to build the shared library and the next major xeus will require cryptopp 8.0 shared.

**Comment by SylvainCorlay** [comment]
I opened https://github.com/conda-forge/cryptopp-feedstock/pull/11 to build the shared library in the conda package for cryptopp.

**Pull request merged**
