### PR TITLE
WIP: Add possibility to restart the kernel

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
It's not yet possible to restart the interpreter without killing it. This is due to: https://github.com/jupyter/jupyter_client/blob/5.2.3/jupyter_client/manager.py#L331. We should maybe change this implementation, instead of [shutting down](https://github.com/jupyter/jupyter_client/blob/5.2.3/jupyter_client/manager.py#L361) the kernel, we should just send a `restart` request

**Comment by SylvainCorlay** [comment]
cc @minrk @takluyver

Should `jupyter_client`'s restart implementation call `shutdown` and `start`?

In `xeus-cling` and `xeus-python`, we could simply create a new instance of the underlying interpreter and keep the ports open etc.

**Comment by minrk** [comment]
It is the responsibility of the manager to restart the process. The kernel should not restart itself.

**Comment by takluyver** [comment]
The manager definitely needs the machinery to restart a kernel by terminating it and starting a new process. It could have an additional 'soft restart' where it asks the kernel to reset itself, but I don't see an advantage to justify the complexity.

**Comment by SylvainCorlay** [comment]
One advantage of a soft restart would be e.g. when connecting to a kernel over ssh, to be able to "reboot"  the interpreter without closing the connection (and starting with new random ports). It may also be faster to restart the interpreter internally?

Besides, what should the kernel do when it gets a `shutdown_request` with restart set to true? Should it just not do anything, given that it will be shut down anyway by the client?

**Comment by takluyver** [comment]
IIRC, the kernel should shutdown on any `shutdown_request`, after replying to acknowledge it. The restart parameter is for if it wants to leave something behind for the replacement kernel, but the parent is still expecting the process to terminate. I suspect that giving the kernel this information might actually be a bad design.

**Comment by SylvainCorlay** [comment]
Gotcha. What was your idea for the kernel nanny wrt to the ssh scenario. I recall from a conversation *a long time ago* that this was something you wanted to address?

**Comment by martinRenou** [comment]
> IIRC, the kernel should shutdown on any shutdown_request, after replying to acknowledge it.

Thanks for the information! We were not shutting down the kernel correctly after the `shutdown_request`, that's why it was slow and why we wanted to find a way to restart the kernel without killing it. I opened an other PR which should fix this issue.

Closing this one

**Comment by SylvainCorlay** [comment]
Thanks for chiming in @minrk @takluyver !

**Pull request closed without merging**
